# cargo-features=[]

[package]
name = "grub-wol-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if-addrs = "0.7"
mdns-sd = "0.5.8"
smol = "1.2.5"
tiny_http = "0.11"
