[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.proto]
path = "./../proto"

[dependencies]
petgraph = "0.6.2"
protocol = "3.4.0"
smol = "1.2.5"
tiny_http = "0.11"
