[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies.proto]
path = "./../proto"

[dependencies]
smol = "1.2.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1", default-features = false }
serde_json = "1.0.91"
log = "0.4.17"
async-channel = "1.8.0"
bincode = "1.3.3"
easy-parallel = "3.2.0"
append-only-vec = "0.1.2"


[dependencies.indexmap]
version = "1.9.2"
features = ["serde"]

[dependencies.hyper]
version="0.14"
features = ["http1","server","client"]
