[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.proto]
path = "./../proto"

[dependencies]
smol = "1.2.5"
tiny_http = "0.11"
thiserror = "1.0.37"
nanoserde = { git = "https://github.com/Eason0729/nanoserde.git"}
