[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.proto]
path = "./../proto"

[dependencies]
smol = "1.2.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1", default-features = false }

[dependencies.indexmap]
version = "1.9.2"
features = ["serde"]

[dependencies.hyper]
version="0.14"
features = ["http1","server","client"]
